package com.google.android.apps.nexuslauncher.logging;

import com.android.launcher3.logging.StatsLogManager;
/* loaded from: classes.dex */
public enum NexusLauncherEvent implements StatsLogManager.EventEnum {
    LAUNCHER_GOOGLE_SEARCHBOX_TAP(502),
    LAUNCHER_GOOGLE_SEARCH_PREFERENCE_TAP_OR_LONG_PRESS(799),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_GOOGLE_SMARTSPACE_PREFERENCES_TAP_OR_LONGPRESS(503),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_GOOGLE_SMARTSPACE_WEATHER_TAP(554),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_GOOGLE_SMARTSPACE_DATE_TAP(555),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_GOOGLE_SMARTSPACE_CARD_TAP(556),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_GOOGLE_APP_SWIPE_LEFT_ENABLED(617),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_GOOGLE_APP_SWIPE_LEFT_DISABLED(618),
    LAUNCHER_GOOGLE_SEARCHBOX_LENS_TAP(653),
    LAUNCHER_GOOGLE_SEARCHBOX_MIC_TAP(654),
    LAUNCHER_GOOGLE_SEARCHBOX_G_TAP(1086),
    LAUNCHER_GOOGLE_ALLAPPS_SEARCHBOX_TAP(699),
    LAUNCHER_GOOGLE_ALLAPPS_SEARCH_CORPUS_CODE(712),
    LAUNCHER_GOOGLE_OPEN_ALLAPPS_WITH_IME_ENABLED(762),
    LAUNCHER_GOOGLE_OPEN_ALLAPPS_WITH_IME_DISABLED(763),
    LAUNCHER_GOOGLE_ALLAPPS_CLEAR_SEARCHBOX_TAP(832),
    LAUNCHER_GOOGLE_ALLAPPS_SEARCH_SESSION_ENTRY(833),
    LAUNCHER_GOOGLE_ALLAPPS_SEARCH_SESSION_EXIT(834),
    LAUNCHER_GOOGLE_ALLAPPS_EMPTY_QUERY_ENTER_KEY_TAP(1379),
    LAUNCHER_GOOGLE_ALLAPPS_EDU_TURNED_ON(840),
    LAUNCHER_GOOGLE_ALLAPPS_EDU_TURNED_OFF(841),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_LAUNCH_ASSISTANT_ATTEMPTED_FROM_NON_PHONE(842),
    LAUNCHER_GOOGLE_ALLAPPS_SLICE_FETCH_REQUESTED(844),
    LAUNCHER_GOOGLE_ALLAPPS_SLICE_FETCH_TIMEDOUT(845),
    LAUNCHER_GOOGLE_ALLAPPS_SLICE_FETCH_SUCCEEDED(846),
    LAUNCHER_GOOGLE_SEARCH_SHOW_KEYBOARD_TAP_OR_LONG_PRESS(869),
    LAUNCHER_GOOGLE_SEARCH_HIDE_KEYBOARD_TAP_OR_LONG_PRESS(868),
    LAUNCHER_GOOGLE_SEARCH_SCREENSHOT_LONGPRESS_SHARE(894),
    LAUNCHER_GOOGLE_SEARCHINAPP_LAUNCH(907),
    LAUNCHER_GOOGLE_ALL_APPS_OPEN_FROM_QSB(909),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_LAUNCH_ASSISTANT_ATTEMPTED_FROM_NON_PHONE(912),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_LAUNCH_ASSISTANT_ATTEMPTED_FROM_NON_PHONE(914),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_LAUNCH_ASSISTANT_ATTEMPTED_FROM_NON_PHONE(915),
    LAUNCHER_GOOGLE_RECENT_WALLPAPER_TAP(922),
    LAUNCHER_GOOGLE_ALL_APPS_ENTRY_WITH_KEYBOARD_ENABLED(938),
    LAUNCHER_GOOGLE_ALL_APPS_ENTRY_WITH_KEYBOARD_DISABLED(939),
    LAUNCHER_GOOGLE_SEARCH_SWIPE_UP_WITH_KEYBOARD_TURNED_ON(957),
    LAUNCHER_GOOGLE_SEARCH_SWIPE_UP_WITH_KEYBOARD_TURNED_OFF(958),
    LAUNCHER_GOOGLE_SEARCH_VALID_IMPRESSION_RENDERED(966),
    LAUNCHER_GOOGLE_SEARCH_RESTORE_LIST_SIZE_AFTER_ACTIVITY_RESTART(1391),
    LAUNCHER_GOOGLE_QSB_EXIT(1046),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_LAUNCH_ASSISTANT_ATTEMPTED_FROM_NON_PHONE(1091),
    LAUNCHER_GOOGLE_SEARCH_EDU_CARD_DISMISS(1092),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_LAUNCH_ASSISTANT_ATTEMPTED_FROM_NON_PHONE(1195),
    LAUNCHER_GOOGLE_SEARCH_QUERY_BUILDER_TAP(1243),
    LAUNCHER_GOOGLE_SEARCH_GMS_PLAY_INIT_CHANNEL(1482),
    LAUNCHER_GOOGLE_SEARCH_GMS_PLAY_CHANNEL_FAIL(1375),
    LAUNCHER_GOOGLE_SEARCH_GMS_PLAY_RESPONSE_NOT_EMPTY(1455),
    LAUNCHER_GOOGLE_SEARCH_GMS_PLAY_EMPTY_COMPONENT_NAME(1477),
    LAUNCHER_GOOGLE_SEARCH_QS_TILE_REMOVE_UNSUPPORTED(1376),
    LAUNCHER_GOOGLE_SEARCH_QS_TILE_FALLBACK_CLICK(1377),
    LAUNCHER_GOOGLE_SEARCH_LEARN_MORE_BUTTON_TAP(1393),
    LAUNCHER_GOOGLE_SEARCH_SETTINGS_BUTTON_TAP(1392),
    LAUNCHER_APP_LAUNCH_PENDING_INTENT_SHOULD_START(1395),
    LAUNCHER_LAUNCH_ASSISTANT_FAILED_NOT_AVAILABLE(1465),
    LAUNCHER_LAUNCH_ASSISTANT_FAILED_SERVICE_ERROR(1466),
    LAUNCHER_LAUNCH_ASSISTANT_SUCCESSFUL_NAV_HANDLE(1467),
    LAUNCHER_LAUNCH_ASSISTANT_SUCCESSFUL_OVERVIEW_ACTION(1468),
    LAUNCHER_LAUNCH_ASSISTANT_SUCCESSFUL_OVERVIEW_MENU(1469),
    /* JADX INFO: Fake field, exist only in values array */
    LAUNCHER_LAUNCH_ASSISTANT_ATTEMPTED_FROM_NON_PHONE(1470),
    LAUNCHER_LAUNCH_OMNI_FAILED_NOT_AVAILABLE(1471),
    LAUNCHER_LAUNCH_OMNI_SUCCESSFUL_HOME(1481),
    LAUNCHER_GOOGLE_ALLAPPS_EDU_TURNED_ON_WITH_ENABLE_SHOW_IME_SNACKBAR_AGAIN(1474),
    LAUNCHER_GOOGLE_ALLAPPS_EDU_TURNED_OFF_WITH_ENABLE_SHOW_IME_SNACKBAR_AGAIN(1475),
    LAUNCHER_READ_OMNI_AVAILABILITY_FROM_APP_SEARCH_FAILED(1484),
    LAUNCHER_LAUNCH_OMNI_ATTEMPTED_OVER_NOTIFICATION_SHADE(1485),
    LAUNCHER_SETTINGS_OMNI_NAV_HANDLE_TOGGLE_VALUE(1486),
    LAUNCHER_SETTINGS_OMNI_HOME_BUTTON_TOGGLE_VALUE(1487),
    LAUNCHER_LAUNCH_OMNI_ATTEMPTED_OVER_KEYGUARD(1501);
    
    private final int mId;

    NexusLauncherEvent(int i4) {
        this.mId = i4;
    }

    @Override // com.android.launcher3.logging.StatsLogManager.EventEnum
    public final int getId() {
        return this.mId;
    }
}
